//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoLocation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoLocationAttendee
    {
        public int ID { get; set; }
        public int GeoLocationID { get; set; }
        public int UserID { get; set; }
    
        public virtual GeoLocation GeoLocation { get; set; }
        public virtual User User { get; set; }
    }
}
